import SideBar from '@/components/sidebar/SideBar'
import './globals.css'
import Providers from './providers'
import Arrange from './arrange'
import { Box } from '@chakra-ui/react'
import HeadBar from '@/components/headbar/HeadBar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Arrange>
            <SideBar />
            <div>
              <HeadBar />
              {children}
            </div>
          </Arrange>
        </Providers>
      </body>
    </html>
  )
}
