import './globals.css'
import RemainingLayout from './remainingLayout'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <RemainingLayout>{children}</RemainingLayout>
      </body>
    </html>
  )
}
